export const boardMembers = [
  // Officers
  {
    name: "Samantha Bowers",
    position: "Chair",
    department: "Phillip J. Bowers & Co.",
    officerOrDirector: "Officer",
    executiveCommitteeMember: true,
  },
  {
    name: "Adam Philipson",
    position: "Vice-Chair",
    department: "Count Basie Center for the Arts",
    officerOrDirector: "Officer",
    executiveCommitteeMember: true,
  },
  {
    name: "Mary DeMont",
    position: "Secretary",
    department: "Barbizon of Red Bank",
    officerOrDirector: "Officer",
    executiveCommitteeMember: true,
  },
  {
    name: "Louis Andreanos",
    position: "Treasurer",
    department: "Neapoli",
    officerOrDirector: "Officer",
    executiveCommitteeMember: true,
  },

  // Directors
  {
    name: "Amy Russo",
    department: "Toast Diner",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Angela Courtney",
    department: "Sweetest Sin Lingerie Shop",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Acya User",
    department: "Antoinette Boulangerie",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Ben Forest",
    position: "Member of Borough Council",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Carl DeAngelis",
    position: "Attorney",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Cassie Murphy",
    position: "Resident representative",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Courtney Schroeder",
    department: "Two River Theater",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Darren McConnell",
    position: "Borough Administrator",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Jay Herman",
    department: "Downtown Investors",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "John Anderson",
    department: "Foss, San Filippo, Milne",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Kate Triggiano",
    position: "Mayor’s Designee",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Kevin Barry",
    department: "The Molly Pitcher Inn",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Lauren Nicosia",
    position: "Resident Representative",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Louis Andreanos",
    department: "Neapoli",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  }, // Note: Duplicate entry in the list, consider if intentional
  {
    name: "Michael DeSimone",
    department: "JR’s Red Bank",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Sam Jain",
    department: "Bombay River",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Sheila Hintze",
    department: "Riverview Medical Center",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Stephen Catania",
    department: "The Cheese Cave",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Steven Denholtz",
    department: "Denholtz Associates",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Steve Raciti",
    position: "Architect",
    department: "",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Erik Horowitz",
    department: "Redwood Real Estate",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Ed McKenna",
    position: "Attorney",
    department: "Ed McKenna Attorney at Law",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Ingeborg Perndorfer",
    department: "The Language School",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Dorothy Sourlis-Whitehouse",
    department: "The Galleria",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Jason Daniels",
    department: "Pilates Plus",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
  {
    name: "Debbie Eisenstein",
    department: "Red Bank Artisan Collective",
    officerOrDirector: "Director",
    executiveCommitteeMember: false,
  },
];
