export const giftCards = [
  { name: "A Time to Kiln" },
  { name: "Azteca Grill" },
  { name: "Basie Center Cinemas" },
  { name: "Bombay River" },
  { name: "Cabana 19" },
  { name: "Center for Pilates" },
  { name: "Chocolate Works" },
  { name: "Elli’s Backyard" },
  { name: "Fins & Feathers" },
  { name: "Forge" },
  { name: "Fourchette" },
  { name: "Georgetown Fine Clothiers" },
  { name: "Good Vibe Nutrition" },
  { name: "Jack’s Music Shop" },
  { name: "L Studio" },
  { name: "Little Waves" },
  { name: "Monmouth Meats" },
  { name: "Monmouth Street Emporium" },
  { name: "Mother Knitter" },
  { name: "Neapoli" },
  { name: "Once Bitten Donuts" },
  { name: "Patrizia’s" },
  { name: "Poor Cat Designs" },
  { name: "Pop Freak Collectibles" },
  { name: "Red Bank Artisan Collective" },
  { name: "Red Bank Chocolate Shop" },
  { name: "Red Bank Diner" },
  { name: "Red Ginger Home" },
  { name: "Reve Salon" },
  { name: "Sally Boy’s" },
  { name: "Sickles Red Bank" },
  { name: "Sorella Bella Boutique" },
  { name: "Sweetest Sin Boutique" },
  { name: "The Art of Jewelry" },
  { name: "The Barefoot Bride" },
  { name: "The Green Room" },
  { name: "The Local Line" },
  { name: "The Robinson Ale House" },
  { name: "Toast City Diner" },
  { name: "Toy Utopia" },
  { name: "Triumph Brewing" },
  { name: "Washington General Store" },
  { name: "Yestercades" },
];
